services:
  php:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    volumes:
      - .:/app
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    tty: true
